In [ ]:
import mysql.connector as a
connect = a.connect(host="localhost", user="root", passwd="1234", database="bank")

def openAccount():
    name = input("Enter Name: ")
    accno = input("Enter Account No: ")
    dob = input("Enter D.O.B: ")
    phone = input("Enter Phone: ")
    email = input("Enter Address: ")
    openbal = int(input("Enter Opening Balance: "))
    data1 = (name, accno, dob, phone, email, openbal)
    data2 = (name, accno, openbal)
    sql1 = 'insert into account values(%s,%s,%s,%s,%s,%s)'
    sql2 = 'insert into amount values(%s,%s,%s)'
    c = connect.cursor()
    c.execute(sql1,data1)
    c.execute(sql2,data2)
    connect.commit()
    print("Data Entered Successfully")
    main()
    
def deposit():
    amount = int(input("Enter Amount: "))
    accno = input("Enter Account No: ")
    a = "select balance from amount where accno = %s"
    data = (accno,)
    c = connect.cursor()
    c.execute(a,data)
    result = c.fetchone()
    total = result[0] + amount
    sql = " update amount set balance = %s where accno = %s"
    d = (total,accno)
    c.execute(sql,d)
    connect.commit()
    main()
    
def withdraw():
    amount = int(input("Enter Amount: "))
    accno = input("Enter Account No: ")
    a = "select balance from amount where accno = %s"
    data = (accno,)
    c = connect.cursor()
    c.execute(a,data)
    result = c.fetchone()
    total = result[0] - amount
    sql = " update amount set balance = %s where accno = %s"
    d = (total,accno)
    c.execute(sql,d)
    connect.commit()
    main()
    
def balance():
    accno = input("Enter Account No: ")
    a = "select balance from amount where accno = %s"
    data = (accno,)
    c = connect.cursor()
    c.execute(a,data)
    result = c.fetchone()
    print("Balance for Account: ", accno," is ",result[0])
    main()
    
def accountInfo():
    accno = input("Enter Account No: ")
    a = "select * from account where accno = %s"
    data = (accno,)
    c = connect.cursor()
    c.execute(a,data)
    result = c.fetchone()
    for i in result:
        print(i, end=" ")
    main()
    
def closeAcc():
    accno = input("Enter Account No: ")
    sql1 = "delete from account where accno= %s"
    sql2 = "delete from account where accno= %s"
    data = (accno,)
    c = connect.cursor()
    c.execute(sql1.data1)
    c.execute(sql2.data2)
    connect.commit()
    main()
    
def main():
    print("""
    1. OPEN NEW ACCOUNT
    2. DEPOSIT AMOUNT
    3. WITHDRAW AMOUNT
    4. BALANCE ENQUIRY
    5. DISPLAY CUSTOMER DETAILS
    6. CLOSE ACCOUNT
    """)
    choice = input("Enter Service No: ")
    while True:
        if (choice == '1'):
            openAccount()
        elif (choice == '2'):
            deposit()
        elif (choice == '3'):
            withdraw()
        elif (choice == '4'):
            balance()
        elif (choice == '5'):
            accountInfo()
        elif (choice == '6'):
            closeAcc()
        else:
            print("Enter a valid number:1,2,3,4,5")
            main()
main()

    1. OPEN NEW ACCOUNT
    2. DEPOSIT AMOUNT
    3. WITHDRAW AMOUNT
    4. BALANCE ENQUIRY
    5. DISPLAY CUSTOMER DETAILS
    6. CLOSE ACCOUNT

Enter Service No: 5
Enter Account No: 1234
Young 1234 01/10.2000 321321 NY 2000
    1. OPEN NEW ACCOUNT
    2. DEPOSIT AMOUNT
    3. WITHDRAW AMOUNT
    4. BALANCE ENQUIRY
    5. DISPLAY CUSTOMER DETAILS
    6. CLOSE ACCOUNT